### ISSUE TITLE
Research and document best practices for grouping resources by project in AWS

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/ops#101]
### Overview
A requirement of the Ops community's [policy levels]() is that level two members have access to some resources attached to a specific project. Hack for L.A. is somewhat unique in that we combine multiple projects into a single incubator account to consolidate management. 

Research and report on the best practice(s) for grouping or identifying AWS resources by projects. One solution may be to tag each resource with a project identifier (i.e. people-depot) and also tag each user with their project identifier(s).

### Action Items
- [x] Document (either inside of this issue or in a doc in the [Ops drive](https://drive.google.com/drive/folders/1XBuLSjOEKGfeVvWluIDyPYXTKHXhYHDM?usp=drive_link)) best practices for grouping resources by project in AWS.

### Resources/Instructions
[IAM Groups & Policies Notes](https://docs.google.com/document/d/1OUwPCzzHa2YROSp7YugYG_LH-NNIiroweqVxxSrQ4gY/edit?usp=sharing)

**Comment by KazushiR** [comment]
@chelseybeck Hello Chelsey, I wasn't so sure on the scope of information you would want and what type of documentation would be needed to be created, such as making a guide or just doing a research on this policy. I have looked into this and found some useful information. I hope this is what is needed for this issue. I have created short bullet points on the use of Tags as I think that is the best option for us. I think the better option might be using IAM conditions. 

**Use of Tags**
-AWS tags may be the best option to categorize resources by purpose/owner/environment
-Can go ahead and use a tag/key value for each AWS resources by projects. 
-AWS will go ahead and check to see if the users is permitted to make actions within a specific resource. 
-To go ahead and use tags, it can be attached or passed in the request to services that support tagging. 
-Tags can be enforced in resources and making requests.
-To enforce tagging, we may need to create an IAM JSON policy element. Best option might be using a condition block to help manage level 2 users. 
-It can have multiple condition operators and each condition operator contain multiple context key-value pairs.

Resources
https://docs.aws.amazon.com/tag-editor/latest/userguide/tagging.html
https://docs.aws.amazon.com/IAM/latest/UserGuide/access_tags.html
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html

**Comment by chelseybeck** [comment]
This is great and exactly the info we needed @KazushiR. We may need to document this further in the future, but I'm confident that we can achieve what is needed by tagging resources w/ project names. ty for the work on this!

**Comment by paulespinosa** [comment]
Does anyone foresee the need to design a tagging strategy and enforce tagging schemes? 

For example: `hfla:cost-allocation:Owner=huu`

* Best Practices for Tagging AWS Resources: https://docs.aws.amazon.com/whitepapers/latest/tagging-best-practices/tagging-best-practices.html
* From the same guide, guidance on iteratively building the tagging strategy: https://docs.aws.amazon.com/whitepapers/latest/tagging-best-practices/building-your-tagging-strategy.html
