### ISSUE TITLE
Create issue template for onboarding new members to DevOps

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/ops#109]
### Dependencies
- [x] #111 

### Overview

When new members onboard to DevOps, we want to ensure they have all the information they need to be successful contributors. 

### Action Items

- [ ] Create an onboarding issue template that lists out steps that new members should take to completely onboard to the CoP
  - join the #ops Slack Channel 

### Resources/Instructions
- [DevOps wiki, Permission levels for team members](https://github.com/hackforla/ops/wiki/Permission-levels-for-Team-Members)
- [Example from website team](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/pre-work-template--dev.md)

**Comment by ExperimentsInHonesty** [comment]
```
#### Initial Onboarding
  - [ ] join the #ops Slack Channel 

#### Proceed through levels of proficiency and responsibility
Use the wiki page listed under resources for the links and instructions for each
- [ ] L1: Learn Terraform
- [ ] L1: Get Access and Submit your first PRs
- [ ] L2: Get assigned to project as their DevOps person
- [ ] L3: Become a mentor across all projects DevOps people
- [ ] L4: Become Supervisor

### Resources/Instructions
- [DevOps wiki, Permission levels for team members](https://github.com/hackforla/ops/wiki/Permission-levels-for-Team-Members)
```

**Comment by sudhara** [comment]
The issue can be marked complete as the work is done.
