### ISSUE TITLE
Update branch protection rules in DevOps Security repo to restrict PR merge to main to merge team

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/ops#110]
### Overview

The DevOps Security repo needs branch protections implemented so that only the devops-security-merge team can merge pull requests into the main branch

### Action Items

- [x] Update branch protections in repo settings that only allow the @hackforla/devops-security-merge team to merge

### Resources/Instructions

[DevOps Security Repo](https://github.com/hackforla/devops-security)
[DevOps Security Merge Team](https://github.com/orgs/hackforla/teams/devops-security-merge)

**Comment by ExperimentsInHonesty** [comment]
Here are the settings in the website repo under Settings > Branches to use as an example
<details><summary>screenshot</summary>
<p>

![screencapture-github-hackforla-website-settings-branch-protection-rules-21239485-2024-01-26-13_23_05](https://github.com/hackforla/expunge-assist/assets/37763229/1e0a8461-05da-43e5-87f9-3be156bdf704)

</p>
</details>
