### ISSUE TITLE
Research tutorials for setting up AWS/Terraform sandbox

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/ops#111]
### Overview
We need to provide tutorials to new DevOps members about how to setup a AWS/Terraform sandbox so that they will be able to use the tutorials we are providing to get them to basic proficiency

#### Details
We want to be able to provide new members resources for getting started contributing to our code repositories. Since we are transitioning to maintaining our infrastructure as code (IaC), we want to be able to guide new members to tutorials that will get them up and running applying Terraform configurations in their own AWS playground.

### Action Items
- [x] Research and list some tutorials for setting up an AWS sandbox to learn/practice.
- [ ] Review with DevOps leads and get sign off
- [ ] Add to wiki under the Learn Terraform part of this page 
- [ ] Release the dependency on #109 and move it into the new issue approval column.

### Resources/Instructions
- [DevOps wiki](https://github.com/hackforla/ops/wiki)
- [DevOps wiki, Permission levels for team members](https://github.com/hackforla/ops/wiki/Permission-levels-for-Team-Members)

**Comment by ExperimentsInHonesty** [comment]
@KazushiR 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by KazushiR** [comment]
@bonniewolfe Hello, I apologize as I have been busy and haven't had time to work on this issue. I will be unassigning myself for the time being.

**Comment by freaky4wrld** [comment]
### List under development
- Articles
   -  [AWS sandbox with terraform](https://blog.devops.dev/how-to-create-an-aws-sandbox-account-using-terraform-c3592a6d8abd)
   - [Creating AWS sandbox]()https://stuffwithaurum.com/2020/05/05/creating-an-aws-sandbox)

**Comment by ExperimentsInHonesty** [comment]
@chelseybeck @freaky4wrld None of the resources, so far, are beginner level.  We are really looking for a Step-by-Step instruction for setting up a free tier AWS account.  We already have the HashiCorp tutorials for people to learn how to use terraform.  But someone who has never set up an AWS account, needs a tutorial that we know, trust, and can become familiar with, so that if they have problems executing it, it will be easy for people who have already done it, to help them.

**Comment by chelseybeck** [comment]
I feel like we do a good job [here](https://github.com/hackforla/devops-security/blob/main/CONTRIBUTING.md#setting-up-the-local-development-environment) of explaining it - which I think also resolves this issue

**Comment by sudhara** [comment]
Issue can be closed
