### ISSUE TITLE
Add a CONTRIBUTING.md to the Ops repo

### ISSUE THREAD

**Issue by freaky4wrld** [hackforla/ops#120]
### Overview

As developers we want to enhance the `ops repo` by adding a CONTRIBUTING.md file. This guide will provide clear instructions for new volunteers on how to contribute to the ops repo. By giving these guidelines, we streamline the contribution process and create a welcoming environment for collaboration.

### Action Items

In the CONTRIBUTING.md guide provide instructions for
- [x] Making contributions to the repo
- [x] Cloning the [ops](https://github.com/hackforla/ops) repo
- [x] Creating a new branch to work on the feature, make sure you provide instructions for the [naming convention](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue)
- [x] Adding, committing and pushing the changes
- [x] Creating a PR

### Resources/Instructions

Example for contributing guide: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
Link to the naming conventions: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue

**Comment by awlFCCamp** [comment]
Availability: 3/22 - 3/24
ETA: EOD 3/25
