### ISSUE TITLE
Update branch protection rules to restrict merges to merge team in this repo

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/ops#121]
### Overview

The devops repo needs branch protections implemented so that only the ops-merge team can merge pull requests into the main branch

### Action Items

- [x] Create devops-merge team
- [x] Add merge team to repo
- [ ] Add team members
- [ ] Update branch protections in repo settings that only allow the @hackforla/devops-merge team to merge

### Resources/Instructions

- https://github.com/orgs/hackforla/teams/ops-security-merge - no members
- https://github.com/orgs/hackforla/teams/ops-merge - no members
- https://github.com/orgs/hackforla/teams/incubator-merge - 8 members

**Comment by sudhara** [comment]
Chelsey cleaning up the merge team members for the devops-security repo. List of members are in the below link.
https://github.com/orgs/hackforla/teams/devops-security-merge
