### ISSUE TITLE
Install Github wiki for Ops repo

### ISSUE THREAD

**Issue by JasonEb** [hackforla/ops#22]
### Overview
Ops would like to have a wiki from the github in order to collect documentation. The wiki content should at least have https://github.com/hackforla/getting-started/issues/9

Given I'm using Github to access the ops repository, 
When I see the various  repo tabs, I should see the Wiki tab. 

### Action Items
- [ ] Investigate Github wiki feature
- [ ] Find any similar HFLA github wiki implementations
- [ ] Add this content under _joining the ops team_
 - https://github.com/hackforla/getting-started/issues/9
 
### Resources/Instructions
https://github.com/hackforla/getting-started/issues/9

[Adding or editing wiki pages](https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages)

**Comment by ExperimentsInHonesty** [comment]
We setup wiki without using the standard style.  But its working fine.
