### ISSUE TITLE
Create Systems Design diagrams for Incubator

### ISSUE THREAD

**Issue by JasonEb** [hackforla/ops#27]
### Overview
As a project stakeholder, I'd like a diagram of resources provisioned by the infrastructure code so I can understand the system from a higher level. 

### Action Items
- [x] Investigate https://github.com/hackforla/incubator/tree/main/incubator
- [x] Internal diagram
- [x] Overview diagram

### Resources/Instructions
https://github.com/hackforla/incubator/tree/main/incubator
https://github.com/hackforla/incubator/wiki/Incubator-System-Design

**Comment by JasonEb** [comment]
https://github.com/hackforla/incubator/wiki/Incubator-System-Design 

Here's the overview design for Incubator

**Comment by ExperimentsInHonesty** [comment]
Here is the file I will download once I setup a figma account and figjam for Ops.

**Comment by ExperimentsInHonesty** [comment]
@jason, I created the [figma account for DevOps](https://www.figma.com/files/team/1145892174954415576/Dev-Ops?fuid=775836858007206739).  So far, only Fang and I have accepted.  The invitations expire, so you should accept it again, but if you don't fang can invite you at the next meeting by clicking on this [members page](https://www.figma.com/files/team/1145892174954415576/Dev-Ops/members?fuid=775836858007206739) and then clicking invite in the top right corner

**Comment by ExperimentsInHonesty** [comment]
I also added this page to the wiki https://github.com/hackforla/ops/wiki/Team-Resources
