### ISSUE TITLE
Create Guide for setting up project.hcl for deploying on Incubator

### ISSUE THREAD

**Issue by JasonEb** [hackforla/ops#31]
### Overview
As an dev ops engineer working with Incubator https://github.com/hackforla/incubator/tree/main/incubator, I would like documentation on setting up `project.hcl` files.

Currently the documentation does capture commands for the Incubator, but lacks documentation on `project.hcl`. These configuration files aren't committed to Github, but instead is maintained in a project's 1password vault.

This guide should clarify
- [ ] What data project.hcl files need to address
- [ ] Workflow for using project.hcl between the project's team and ops

### Action Items
- [x] Coordinate a project.hcl session with Darren
- [ ] Draft documentation

### Resources/Instructions
https://github.com/hackforla/incubator/tree/main/incubator

**Comment by ExperimentsInHonesty** [comment]
Is this still going to be needed?  Or will this be replaced by data stored in a github repo's secrets?

**Comment by nyarly** [comment]
This is going to be replaced, yes. I've started the process of adding a new project with Access the Data, and am sketching docs as I go

**Comment by ExperimentsInHonesty** [comment]
@chelseybeck I can't tell if this information has been replaced in the [incubator wiki](https://github.com/hackforla/incubator/wiki/Incubator-usage).  I see that references to HCL files are marked as legacy... but I am not clear what is replacing it.  I also don't know if that matters to us closing this issue.  Thoughts?

**Comment by sudhara** [comment]
We no longer have hcl files and hence this issue is not needed.
