### ISSUE TITLE
Adapt Incubator Documentation into Incubator wiki

### ISSUE THREAD

**Issue by JasonEb** [hackforla/ops#47]
### Overview
Currently, technical documentation is hosted within Incubator's repo. As as project stakeholder, I would like to have to technical documentation in the wiki so I can begin deploying my project to HFLA's incubator. 

### Action Items
- [ ] Audit https://github.com/hackforla/incubator/tree/main/documentation
  - double-check branches to see if there's any other articles 
- [ ] Move articles with content to https://github.com/hackforla/incubator/wiki

### Resources/Instructions
https://github.com/hackforla/incubator/tree/main/documentation

**Comment by joshuayhwu** [comment]
@JasonEb See below:

```
$ git push --set-upstream origin newWiki
remote: Permission to hackforla/incubator.wiki.git denied to joshuayhwu.
fatal: unable to access 'https://github.com/hackforla/incubator.wiki.git/': The requested URL returned error: 403
```

Any thoughts on setting git permissions?

**Comment by JasonEb** [comment]
@joshuayhwu I added you to ops and ops-write on Github, but you shouldn't have write markdown and git push from our local machine. You should be able to see the `Wiki` tab in the repo now and be able to directly edit the markdown in the Wiki. Lmk if that's not the case for you
![image](https://user-images.githubusercontent.com/6300995/188015131-a1eb551b-a956-467d-bc9d-ff50ac94eb65.png)

**Comment by JasonEb** [comment]
Hey Josh, whenever good - please provide an update with this template. Lmk if you have any issues

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by JasonEb** [comment]
Hey Josh, whenever good - please provide an update with this template. Lmk if you have any issues

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."
remember to add links to the top of the issue if they are going to be needed again.

**Comment by joshuayhwu** [comment]
Progress: completed at the [ops wiki page](https://github.com/hackforla/ops/wiki).
Blockers: none.
Availability: depending on new job hours.
ETA: done

P.S.: If it's on the wrong wiki, simply copy the part from "Incubator Hosting" to "Dedicated Hosting" and move to wherever desire.
