### ISSUE TITLE
Create Figma document from Incubator System Design 

### ISSUE THREAD

**Issue by JasonEb** [hackforla/ops#49]
### Overview
Currently, we have Incubator system design diagram hosted here https://github.com/hackforla/incubator/wiki/Incubator-System-Design

Given I'm a Dev Ops Team Member, I'd like to have a Figma document version off the diagram mentioned above. 

### Action Items
- [x] Create Figma document

### Resources/Instructions
[System Diagram hosted in Wiki. Use for reference with Figma.](https://github.com/hackforla/incubator/wiki/Incubator-System-Design)
[Prior Issue related to Diagram](https://github.com/hackforla/ops/issues/27#issuecomment-1229573808)

**Comment by Carter-tc** [comment]
I created the diagram using Figma.
https://www.figma.com/file/dQDNBviT3U8srPyohucyiw/Containerized-Architecture?node-id=0%3A1

**Comment by Carter-tc** [comment]
Do the images need to be included?

**Comment by JasonEb** [comment]
@Carter-tc that looks good, and yeah we'll need to have AWS images for those icons. Bonnie shared this template here https://www.figma.com/file/eF4dhHtsBVRV2Zk3Zb0bCd/AWS-Cloud-Diagram-Template-(Community)?node-id=0%3A1. You can duplicate it and edit it to extract the icons. 

So for DNS, that is Amazon's "Route 53" service, so we'll use that icon in the template file. 
![image](https://user-images.githubusercontent.com/6300995/188758481-08292b41-745f-4431-9cc2-f57ecd956143.png)

Match these 3 icons. For the App stack, that looks well 

![image](https://user-images.githubusercontent.com/6300995/188758566-6d2a7926-4288-4fe1-bcca-7e0d190b59c5.png)

**Comment by JasonEb** [comment]
Load Balancer Icon is now orange 
![image](https://user-images.githubusercontent.com/6300995/188758868-34bf3433-f4ac-4b6f-bea5-1ee8473c68c1.png)

**Comment by JasonEb** [comment]
Please provide update, whenever good
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by JasonEb** [comment]
This looks good!

![image](https://user-images.githubusercontent.com/6300995/191633392-5766cf29-a34d-487a-9b31-d915214f0522.png)
