### ISSUE TITLE
Diagram active Incubator applications 

### ISSUE THREAD

**Issue by JasonEb** [hackforla/ops#53]
### Overview
As a Dev Ops member, I'd like to have a diagram of what hackforla software are active under the Incubator infrastructure. 

Once this is determines, ops can then update the Incubator repo to reflect the current list of software. 

### Action Items
- [ ] Access AWS incubator account
- [ ] Examine ECR list 
- [ ] Use Figma/Draw.io to for diagramming
- [ ] Add diagrams to GH Wiki

### Resources/Instructions
https://www.figma.com/file/dQDNBviT3U8srPyohucyiw/Containerized-Architecture?node-id=676%3A331

**Comment by JasonEb** [comment]
Hey Carter, lets provide an update whenever good 
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by Carter-tc** [comment]
Accessed the AWS account. There are no repositories displayed on the ECR list.

**Comment by Carter-tc** [comment]
I have done the first 2 steps but ran into an error code when trying to create a repository. 
<img width="941" alt="Authorization Error" src="https://user-images.githubusercontent.com/96758314/193984543-ffed32ea-e904-4a99-b8fd-46b1248379bf.png">

**Comment by Carter-tc** [comment]
I can determine how long the task will take once I can see the full scope of a repository and the tools offered

**Comment by JasonEb** [comment]
> I have done the first 2 steps but ran into an error code when trying to create a repository. <img alt="Authorization Error" width="941" src="https://user-images.githubusercontent.com/96758314/193984543-ffed32ea-e904-4a99-b8fd-46b1248379bf.png">

You don't have to create new repositories for this issue, only to examine the current ones

**Comment by JasonEb** [comment]
Hey Carter, lets provide an update whenever good

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

**Comment by Carter-tc** [comment]
All Repositories have been added to the Figma diagram

**Comment by ExperimentsInHonesty** [comment]
@Carter-tc @JasonEb Is this issue completed?  It's still open, and it has not been commented on since 2022

**Comment by Carter-tc** [comment]
I believe it was completed. Any comment Jason?

Best,
Tahnea Carter

**Comment by chelseybeck** [comment]
The link in the resources above show that this has been completed.
