### ISSUE TITLE
Install 2 week inactive GitHub Automation

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/ops#58]
### Overview
We need to install a GHA that reminds assignees to provide an update weekly, so that we can maintain momentum on our projects

### Action Items
- [x] Review Bonnie's overview
- [x] Review the GHA that the website team has built
- [x] Write up the changes you will need to make for the code to work on the ops repo
- [x] review the proposed change with the ops team
- [x] do a PR that installs custom version for the ops team
- [x] test

### Resources/Instructions
- GHA that website team uses: https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly
- Bonnie's overview of how it works https://github.com/ExperimentsInHonesty/bonnie-talks/blob/main/resources/please-provide-update.md

**Comment by ExperimentsInHonesty** [comment]
Add link to existing GHA how to documentation

**Comment by chelseybeck** [comment]
Moved this to new issue review for refinement. The links are broken on the website wiki and I can't find their equivalent in the website repo.

**Comment by joey-ma** [comment]
It's nice to be able to reference something that is already there (and it looks like it is working). 

@ExperimentsInHonesty the [add-label.js](https://github.com/hackforla/website/blob/9913ae68a679067f006dfcd4055e23cd009b5474/github-actions/trigger-schedule/add-update-label-weekly/add-label.js) seems to do a bit more than "remind assignees to provide an update weekly", does implementing exactly the same for `ops` sound good?

**Comment by chelseybeck** [comment]
@joey-ma how's this going?

**Comment by joey-ma** [comment]
hi @chelseybeck, sorry didn't have time to work on this sooner! but I couldn't sleep so here I am 😄 I think most of the work is done and will open a draft MR next; just copied over and refactored, so I think this should work pending final tweaks and setup. Here's my (draft) [MR](https://github.com/hackforla/ops/pull/122)!
