### ISSUE TITLE
Point the DNS for CivicTechJobs.org To AWS incubator

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/ops#64]
### Overview
We ready to have the domain name pointed to our hosting instance so that we can have a dev or prod instance.

### Action Items
- [x] Indicate if the instance will be for Dev or Prod or both
- [x] Indicate in the URLs you will need (including subdomains)
- [x] Provide the DNS to point to
- [x] Provide any information for CNAME and A records
- [x] Provide date that the domain should go live
- [x] Provide preview of the Coming Soon page that will appear on the domain name until the website has been finished

### Resources/Instructions
Where the domain name is hosted: Hack for LA's Google Domains Account

### Dev
https://stage.civictechjobs.org

### Prod
https://civictechjobs.org
https://www.civictechjobs.org

**Comment by chelseybeck** [comment]
@Enzyme3 do you know the status of this issue?

**Comment by chelseybeck** [comment]
this is done
