### ISSUE TITLE
New AWS account for Davon Webb

### ISSUE THREAD

**Issue by davon24** [hackforla/ops#79]
### Overview

As a new member of the Ops team, Davon will need AWS account with relevant permissions

### Action Items

- [ ] Create the AWS account
- [ ] Add the account to the necessary group(s) for his role

### Resources/Instructions

[Resources](https://github.com/hackforla/ops/wiki)

**Comment by KazushiR** [comment]
Hey Davon, I just set up a profile for you for your AWS account.
