### ISSUE TITLE
Review new Recruiting Pipeline channel

### ISSUE THREAD

**Issue by Civic-Opportunity-Project** [hackforla/ops#8]
[Pipeline sheet](https://docs.google.com/spreadsheets/d/1sPu4ylVz20SHYSezoo_DDO_gh1ifv0VE2QlCoFwRaRA/edit)

- [ ] Review Value in column D (Value in column C) in Row 1
- [ ] Set Display value (column L) to TRUE or FALSE

**Comment by rjdoria** [comment]
Zapier test completed.
