### ISSUE TITLE
Create AWS IAM user account for Antonina

### ISSUE THREAD

**Issue by VAntonina** [hackforla/ops#80]
### Overview
Create AWS IAM user account for a team member in order to grant access for managing purposes. 

### Action Items
Create a user with username **antonina_v**
Autogenerate temporary password
Tag slack_id, and tag email
Place account in ops IAM Group
Send csv of credentials to the requester

### Resources/Instructions
https://github.com/hackforla/ops/wiki/AWS-User-Management

**Comment by KazushiR** [comment]
created a user account and assigned them to Groups.
