### ISSUE TITLE
[SPIKE] Set up AWS  billing notifications alarms 

### ISSUE THREAD

**Issue by JasonEb** [hackforla/ops#86]
### Overview
Currently, we have no safe guards in place if an AWS service costs more than anticipated. AWS has measures in place with tools like Cloudwatch. Let's investigate how to set up a cloudwatch alarm and see if we can set up notifications

### Action Items
- [x] Investigate HFLA's incubator AWS setup
- [x] Determine a general implementation and potential costs
  - [x] Determine how and who gets notifications 
- [ ] Create implementation issue
- [ ] Create CloudWatch documentation issue 

### Resources/Instructions
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/monitor_estimated_charges_with_cloudwatch.html

**Comment by JasonEb** [comment]
is there a way to shut down services when they exceed costs?

**Comment by akashsky1994** [comment]
We can divide our cost management notifications and thresholds into three parts:

1.  Cost Estimation While Spinning up new resource
Considering that we have started using terraform, we can take a look at Infracost. In short, it checks your tfplan file and gives an estimate of the cost. You can checkout this link for exact usage: https://getbetterdevops.io/cloud-cost-estimation-with-terraform/

2. Notifications on Email and Slack using Cloudwatch Billing alarms 
	- If we only want notification when our usage cost exceeds the threshold, we can setup simple Billing alarms 
	- From what the documentation, it seems like we have limited actions option within cloudwatch as it only allows us to stop EC2 instances.
	- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/monitor_estimated_charges_with_cloudwatch.html
	- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/UsingAlarmActions.html
	
3. Using AWS Budgets and Budget Actions
	- https://docs.aws.amazon.com/cost-management/latest/userguide/budgets-controls.html
	- We can implement both Alert and Termination action for the resources. This much more geared towards cost management as compared to Cloudwatch billing Alarms
	- https://docs.aws.amazon.com/cost-management/latest/userguide/budgets-controls.html

**Comment by JasonEb** [comment]
I think for this SPIKE ticket, let's limit the scope to notifications to Email(s) and possibly Slack. I'll setup a new SPIKE ticket for AWS budget exploration
