### ISSUE TITLE
Review new Recruiting Pipeline channel

### ISSUE THREAD

**Issue by Civic-Opportunity-Project** [hackforla/ops#9]
[Pipeline sheet](https://docs.google.com/spreadsheets/d/1sPu4ylVz20SHYSezoo_DDO_gh1ifv0VE2QlCoFwRaRA/edit)

- [ ] Review Test Channel (Slack Workspace) in Row 2
- [ ] Set Display value (column L) to TRUE or FALSE

**Comment by rjdoria** [comment]
Zapier test completed. Pipeline doc now live.
