### ISSUE TITLE
Document current AWS Permission management practices

### ISSUE THREAD

**Issue by JasonEb** [hackforla/ops#95]
### Dependency
- [ ] If we still need this issue after we have setup each of the new level 1-6 user level groups. 

### Overview
As a dev ops person, I'd like to have documentation covering creating, updating, and deleting aws permissions. 

### Action Items
- [ ] Should capture process in a Wiki
- [ ] Should have visual aid
- [ ] Should highlight various user groups and their permissions
- [ ] Should have a json example
- [ ] Should have a organization process / protocol declared (who gets to ask who?)
- [ ] Should show to manage a single permission
- [ ] Should show how to manage a custom policy 
- [ ] Should show how to add to User Groups
- [ ] Should have a comment about how user groups are managed with permissions
  - [ ] Instead of creating a group with extra permissions, create a group with the specific permissions then add users to that

### Resources/Instructions
- [AWS Documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html)

- [Creating Levels](https://github.com/hackforla/ops/issues/12#issuecomment-1897536015)

**Comment by sudhara** [comment]
As we are managing the users via Terraform code, this issue is not relevant anymore.
