### ISSUE TITLE
Document current AWS User Groups

### ISSUE THREAD

**Issue by JasonEb** [hackforla/ops#96]
### Dependency
- [ ] If we still need this issue after we have set up each of the new level 1-6 user level groups. 

### Overview
As a dev ops person, I'd like there to be documentation covering the different AWS User Groups 

### Action Items
- [ ] Should address current groups and identify key permissions (updating vs reading)
- [ ] Should create document in H4LA's Ops Google Drive directory
- [ ] Should export Permissions view 
  - [ ] https://docs.google.com/spreadsheets/d/1XsbqQoDIYftw9P1P7453oFVYQbH0jpNihQ2QxMXYHuU/edit#gid=0
![image](https://github.com/hackforla/ops/assets/6300995/b6fae65f-33fa-4fa6-8815-a5f14f97c4dd)

### Resources/Instructions
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_groups.html

**Comment by chelseybeck** [comment]
Unplanned. We will identify who needs read-only or higher access and create separate issues.
